### ISSUE TITLE
Compatible with doctrine/doctrine-fixtures-bundle?

### ISSUE THREAD

**Issue by alpha1125** [MJKruszewski/plumbok-bundle#1]
System:
PHP 7.2.15
Symfony 4.2.4

In phpStorm v2018.3.4, it sees plumbok annotation, and able to help with the autocomplete.
I am able to access plumbok annotations from the symfony controllers and doctrine...

however, I am not able to get doctrine/doctrine-fixtures-bundle to work.

When I run doctrine-fixtures-bundle, and trying to access @Setter or @Getter I get the following:

```                                                                                          
  Attempted to call an undefined method named "setName" of class "App\Entity\Question".  
```

Thanks,

**Comment by MJKruszewski** [comment]
@alpha1125 hey, check update in last commit, issue is present due to incompatibility in config paths for Doctrine ORM, after this change autoloading should work correctly for ORM, Console and standard application.

Please share feedback if this resolves your issue to close ticket.
